;==================================================================================================
; Large.inc
;
; This file defines sizes and positions for the "large" sized skins of your package.
; It makes sense to define these in a separate file and only once if you have several skins that 
; use the same visual layout.
;

[Variables]

;
; Canvas size and positions
;
CanvasWidth=360
CanvasHeight=72

;
; Font size
;
FontSize=12

