;==================================================================================================
; Mesium.inc
;
; This file defines sizes and positions for the "medium" sized skins of your package.
; It makes sense to define these in a separate file and only once if you have several skins that 
; use the same visual layout.
;

[Variables]

;
; Canvas size and positions
;
CanvasWidth=320
CanvasHeight=64

;
; Font size
;
FontSize=10

