;==================================================================================================
; Metadata.inc
;
; This file defines the global Metadata settings.
;

;------------------------------------------------------------------------------
;
[Metadata]
;
Name=Grayhound
Author=George Lewe
Version=1.0.0
License=Creative Commons BY-NC-SA 3.0
Information=Documentation: https://support.lewe.com/doc/rainmeter-skin-template/|Source: https://github.com/glewe/rmskintemplate
